<?php
/**
 * Implementation of hook_block_info().
 */
function available_now_block_info() {
  $blocks = array();
  $blocks['available-now'] = array(
    'info' => t('Available Now'),
    'pages' => 'home'
  );
  return $blocks;
}

function available_now_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'available-now':
    /*START LABSTATS FOR COMPUTER AVAILABILITY*/
      $ini = ini_set("soap.wsdl_cache_enabled","0");
      $client = new SoapClient("http://cas.uta.edu/LabStats/WebServices/Statistics.asmx?WSDL");
      $results = $client->GetGroupedCurrentStats()->GetGroupedCurrentStatsResult->GroupStat;
      global $centralCompAvail;
      foreach ($results as $entry) {
        if ($entry->groupName == 'Science and Engineering Library') {
          $selCompAvail = $entry->availableCount;
        } 
        if (strpos($entry->groupName, 'Central') !==false) {
          $centralCompAvail = $centralCompAvail + $entry->availableCount; 
        } 
        if ($entry->groupName == 'Architecture and Fine Arts Library') {
          $afaCompAvail = $entry->availableCount;
        }
      }
    /*END LAB STATS FOR COMPUTER AVAILABILITY*/
    /*START NEW OPENROOM*/
    $html = file_get_contents("https://openroom.uta.edu/or-available.php");
    $doc = new DOMDocument();
    libxml_use_internal_errors(TRUE);
    if (!empty($html)) {
      $doc->loadHTML($html);
      libxml_clear_errors();
      $doc_xpath = new DOMXPATH($doc);
      $centralRooms = $doc_xpath->query('//div[(@id="rooms_cen")]');
      if ($centralRooms->length > 0) {
        $centralRoomAvail = $centralRooms->item(0)->nodeValue;
      }
      $afaRooms = $doc_xpath->query('//div[(@id="rooms_afa")]');
      if ($afaRooms->length > 0) {
        $afaRoomAvail = $afaRooms->item(0)->nodeValue;
      }
      $selRooms = $doc_xpath->query('//div[(@id="rooms_sel")]');
      if ($selRooms->length > 0) {
        $selRoomAvail = $selRooms->item(0)->nodeValue;
      }
    } else {
      $centralRoomAvail = "Information not available";
      $afaRoomAvail = "Information not available";
      $selRoomAvail = "Information not available";

    }
    /*END NEW OPEN ROOM*/
    /*START LAPTOPS*/
    $html = file_get_contents("https://pulse.uta.edu/vwebv/laptops.cgi");
    $doc = new DOMDocument();
    libxml_use_internal_errors(TRUE);
    if (!empty($html)) {
      $doc->loadHTML($html);
      libxml_clear_errors();
      $doc_xpath = new DOMXPATH($doc);
      $centralLaptops = $doc_xpath->query('//div[(@id="laptops_central")]');
      if ($centralLaptops->length > 0) {
        $centralLaptopAvail = $centralLaptops->item(0)->nodeValue;
      }
      $afaLaptops = $doc_xpath->query('//div[(@id="laptops_afa")]');
      if ($afaLaptops->length > 0) {
        $afaLaptopAvail = $afaLaptops->item(0)->nodeValue;
      }
      $selLaptops = $doc_xpath->query('//div[(@id="laptops_sel")]');
      if ($selLaptops->length > 0) {
        $selLaptopAvail = $selLaptops->item(0)->nodeValue;
      }
      else {
        $centralLaptopAvail = "Information not available";
        $afaLaptopAvail = "Information not available";
        $selLaptopAvail = "Information not available";

      }
    }
    /*END LAPTOPS*/
$block_content = '<div class="row">
          <div class="col-sm-12">
            <h2 class="block-title">Available Now </h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 available-now-content">
            <div class="table-responsive">
              <table class="table table-hover">
                 <tr>
                  <th>Technology</th>
                  <th>Central Library</th>
                  <th>Architecture &amp; Fine Arts Library</th>
                  <th>Science &amp; Engineering Library</th>
                </tr>
                <tr>
                  <td><a href="technology/laptops">Laptops</a></td>
                  <td>';
                    $block_content .= $centralLaptopAvail;
                    $block_content .= '</td>
                  <td>';
                      $block_content .= $afaLaptopAvail;
                      $block_content .= '</td>
                  <td>';
                    $block_content .= $selLaptopAvail;
                    $block_content .= '</td>
                </tr>
                <tr>
                  <td><a href="http://cas.uta.edu/CAS/">Computers</a></td>
                  <td>';
                    $block_content .= $centralCompAvail;
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $afaCompAvail; 
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $selCompAvail; 
                    $block_content .= '</td>
                </tr>
                <tr>
                  <td><a href="http://library.uta.edu/study-spaces">Study Rooms</a></td>
                  <td>';
                      $block_content .= $centralRoomAvail;
                      $block_content .= '</td>
                  <td>';
                    $block_content .= $afaRoomAvail;
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $selRoomAvail;
                    $block_content .= '</td>
                </tr>
              </table>
              </div>    
          </div> <!-- end.col-md-12 -->
      </div>';


      $block['subject'] = t("Available Now");
      $block['content'] = $block_content;
      break;
  }
  return $block;
}

?>