<?php
/**
 * Implementation of hook_block_info().
*/
function available_now_block_info() {
  $blocks = array();
  $blocks['available-now'] = array(
    'info' => t('Available Now'),
    'pages' => 'home'
  );
  return $blocks;
}

function available_now_block_view($delta='') { 
  $block = array();
  switch ($delta) {
    case 'available-now': 
	
    /*START LABSTATS FOR COMPUTER AVAILABILITY*/
      $ini = ini_set("soap.wsdl_cache_enabled","0");
      $client = new SoapClient("http://cas.uta.edu/LabStats/WebServices/Statistics.asmx?WSDL");
      $results = $client->GetGroupedCurrentStats()->GetGroupedCurrentStatsResult->GroupStat;
      global $centralCompAvail;
      foreach ($results as $entry) {
        if ($entry->groupName == 'Science and Engineering Library') {
          $selCompAvail = $entry->availableCount;
        } 
        if (strpos($entry->groupName, 'Central') !==false) {
          $centralCompAvail = $centralCompAvail + $entry->availableCount; 
        } 
        if ($entry->groupName == 'Architecture and Fine Arts Library') {
          $afaCompAvail = $entry->availableCount;
        }
      }
    /*END LAB STATS FOR COMPUTER AVAILABILITY*/
    /*START NEW OPENROOM*/
    $html = file_get_contents("https://openroom.uta.edu/or-available.php");
    $doc = new DOMDocument();
    libxml_use_internal_errors(TRUE);
    if (!empty($html)) {
      $doc->loadHTML($html);
      libxml_clear_errors();
      $doc_xpath = new DOMXPATH($doc);
      $centralRooms = $doc_xpath->query('//div[(@id="rooms_cen")]');
      if ($centralRooms->length > 0) {
        $centralRoomAvail = $centralRooms->item(0)->nodeValue;
      }
      $afaRooms = $doc_xpath->query('//div[(@id="rooms_afa")]');
      if ($afaRooms->length > 0) {
        $afaRoomAvail = $afaRooms->item(0)->nodeValue;
      }
      $selRooms = $doc_xpath->query('//div[(@id="rooms_sel")]');
      if ($selRooms->length > 0) {
        $selRoomAvail = $selRooms->item(0)->nodeValue;
      }
    } else {
      $centralRoomAvail = "Information not available";
      $afaRoomAvail = "Information not available";
      $selRoomAvail = "Information not available";

    }
    /*END NEW OPEN ROOM*/
  	
    /*GET JSON DATA FOR DEVICES*/
	$json = file_get_contents("https://pulse.uta.edu/vwebv/devices.cgi");
	$data =  json_decode($json, true);
	
	/*START LAPTOPS*/
	if (isset($data)) {
	$centrallaptops = $data['laptops']['cen'];
	$afalaptops = $data['laptops']['afa'];
	$sellaptops = $data['laptops']['sel'];
	}
	else {
		$centrallaptops = "Information not available";
		$afalaptops = "Information not available";
		$sellaptops = "Information not available";
	}
	/*END LAPTOPS*/
	
		/*START IPADS*/
	if (isset($data)) {
	$centralipads = $data['ipads']['cen'];
	$afaipads = $data['ipads']['afa'];
	$selipads = $data['ipads']['sel'];
	}
	else {
		$centralipads = "Information not available";
		$afaipads = "Information not available";
		$selipads = "Information not available";
	}
	/*END IPADS*/

		/*START MACBOOKS*/
	if (isset($data)) {
	$centralmacbooks = $data['macbooks']['cen'];
	$afamacbooks = $data['macbooks']['afa'];
	$selmacbooks = $data['macbooks']['sel'];
	}
	else {
		$centralmacbooks = "Information not available";
		$afamacbooks = "Information not available";
		$selmacbooks = "Information not available";
	}
	/*END MACBOOKS*/
	
		/*START CHROMEBOOKS*/
	if (isset($data)) {
	$centralchromebooks = $data['chromebooks']['cen'];
	$afachromebooks = $data['chromebooks']['afa'];
	$selchromebooks = $data['chromebooks']['sel'];
	}
	else {
		$centralchromebooks = "Information not available";
		$afachromebooks = "Information not available";
		$selchromebooks = "Information not available";
	}
	/*END CHROMEBOOKS*/
	
		/*START SURFACE TABLETS*/
	if (isset($data)) {
	$centralsurfaces = $data['surfaces']['cen'];
	$afasurfaces = $data['surfaces']['afa'];
	$selsurfaces = $data['surfaces']['sel'];
	}
	else {
		$centralsurfaces = "Information not available";
		$afasurfaces = "Information not available";
		$selsurfaces = "Information not available";
	}
	/*END SURFACE TABLETS*/

$block_content = '<div class="row">
          <div class="col-sm-12">
            <h2 class="pane-title">Available Now </h2>
          </div>
        </div>
        <div class="row">
            <div class="table-responsive">
              <table class="table table-hover table-border">
                 <tr>
                  <th>&nbsp;</th>
                  <th>Central Library</th>
                  <th>Architecture &amp; Fine Arts Library</th>
                  <th>Science &amp; Engineering Library</th>
                </tr>
                <tr>
                  <td><a href="//library.uta.edu/study-spaces">Study Rooms</a></td>
                  <td>';
                      $block_content .= $centralRoomAvail;
                      $block_content .= '</td>
                  <td>';
                    $block_content .= $afaRoomAvail;
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $selRoomAvail;
                    $block_content .= '</td>
                </tr>
                 <tr>
                  <td><a href="//cas.uta.edu/CAS/">Computers</a></td>
                  <td>';
                    $block_content .= $centralCompAvail;
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $afaCompAvail; 
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $selCompAvail; 
                    $block_content .= '</td>
                </tr>
                <tr>
                  <td><a href="//library.uta.edu/technology/dell-laptop">Laptops</a></td>
                  <td>';
                    $block_content .= $centrallaptops;
                    $block_content .= '</td>
                  <td>';
                      $block_content .= $afalaptops;
                      $block_content .= '</td>
                  <td>';
                    $block_content .= $sellaptops;
                    $block_content .= '</td>
                </tr>

               <tr>
                  <td><a href="//library.uta.edu/technology/ipad-air-2">iPads</a></td>
                  <td>';
                      $block_content .= $centralipads;
                      $block_content .= '</td>
                  <td>';
                    $block_content .= $afaipads;
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $selipads;
                    $block_content .= '</td>
                </tr>

                <tr>
                  <td><a href="//library.uta.edu/technology/macbook">MacBooks</a></td>
                  <td>';
                      $block_content .= $centralmacbooks;
                      $block_content .= '</td>
                  <td>';
                    $block_content .= $afamacbooks;
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $selmacbooks;
                    $block_content .= '</td>
                </tr>

                <tr>
                  <td><a href="//library.uta.edu/technology/acer-chromebook">Chromebooks</a></td>
                  <td>';
                      $block_content .= $centralchromebooks;
                      $block_content .= '</td>
                  <td>';
                    $block_content .= $afachromebooks;
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $selchromebooks;
                    $block_content .= '</td>
                </tr>
                <tr>
                  <td><a href="//library.uta.edu/technology/surface-tablet">Surface Tablets</a></td>
                  <td>';
                      $block_content .= $centralsurfaces;
                      $block_content .= '</td>
                  <td>';
                    $block_content .= $afasurfaces;
                    $block_content .= '</td>
                  <td>';
                    $block_content .= $selsurfaces;
                    $block_content .= '</td>
                </tr>
              </table>
              </div>    
         </div>';


      $block['subject'] = t("Available Now");
      $block['content'] = $block_content;
      break;
  }
  return $block;
} 

?>