<?php
/**
 * Implementation of hook_block_info().
 */


function spco_flickr_block_info() {
  $blocks = array();
  $blocks['spco-flickr'] = array(
    'info' => t('SPCO Flickr'),
    'pages' => 'spco'
  );
  return $blocks;
}

function spco_flickr_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'spco-flickr':
    global $block_content;
    require_once('spco_flickr.php');
      $block['subject'] = t("SPCO Flickr");
      $block['content'] = $block_content;
      break;
  }
  return $block;
}

?>