<?php
/**
 * Implementation of hook_block_info().
 */
function libhours_block_info() {
  $blocks = array();
  $blocks['current-hours'] = array(
    'info' => t('Current Hours'),
    'pages' => 'home'
  );
  return $blocks;
}

function libhours_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'current-hours':
    $date = date('Y-m-d');
    $block_content = "<h3>Today's Hours</h3><div class='hours-block'>";
    $result = db_query('SELECT nid, start_time, end_time FROM opening_hours WHERE date =:today ORDER BY nid = 202, nid asc', array(':today'=> $date));


      foreach ($result as $record) {
     $result2 = db_query('SELECT title FROM node WHERE nid =:nid', array(':nid'=>$record->nid));
      foreach ($result2 as $record2) {
         $block_content .= "<a href='node/" . $record->nid . "'>" . $record2->title . "</a><br/>";
         if ($record->start_time == '00:00:00' && $record->end_time == '00:00:00') {
            $block_content .= "<span class='hours'>24 hours</span>";
         } 
         else {
            if ($record->start_time == '00:00:00') {
              $start_time = "Midnight";
           }
           else {
              if (strpos($record->start_time,':30')) {
                  $start = strtotime($record->start_time);
                  $start_time = date('g:i a', $start);
              } else {
                $start = strtotime($record->start_time);
                $start_time = date('g a', $start);
              }
                $start_num = substr($start_time, 0, -2);
                $start_meridium = substr($start_time, -2);
                $start_arr = str_split($start_meridium);
                $start_ampm = $start_arr[0] . "." . $start_arr[1] . ".";
                $start_time = $start_num . $start_ampm;
           }
           if ($record->end_time == '00:00:00') {
              $end_time = "Midnight";
           }
           else {
              if (strpos($record->end_time,':30')) {
                  $end = strtotime($record->end_time);
                  $end_time = date('g:i a', $end);
              } else {
                $end = strtotime($record->end_time);
                $end_time = date('g a', $end);
              }
              $end_num = substr($end_time, 0, -2);
              $end_meridium = substr($end_time, -2);
              $end_arr = str_split($end_meridium);
              $end_ampm = $end_arr[0] . "." . $end_arr[1] . ".";
              $end_time = $end_num . $end_ampm;
           }
            $block_content .= "<span class='hours'>" . $start_time . " - " . $end_time . "</span>";
        }
      }
    }

      $block_content .= "<a href='hours'>All Hours</a></div>";

      $block['subject'] = t("Today's Hours");
      $block['content'] = $block_content;
      break;
  }
  return $block;
}

?>