<?php
/**
 * @file
 * academic_plaza.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function academic_plaza_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'changed\' => NULL,
      \'comment\' => \'0\',
      \'created\' => NULL,
      \'current_revision_id\' => \'4446\',
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_body2\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1\',
            \'revision_id\' => \'1\',
          ),
          array(
            \'value\' => \'15\',
            \'revision_id\' => \'15\',
          ),
          array(
            \'value\' => \'11\',
            \'revision_id\' => \'11\',
          ),
          array(
            \'value\' => \'4\',
            \'revision_id\' => \'4\',
          ),
          array(
            \'value\' => \'10\',
            \'revision_id\' => \'10\',
          ),
          array(
            \'value\' => \'9\',
            \'revision_id\' => \'9\',
          ),
          array(
            \'value\' => \'14\',
            \'revision_id\' => \'14\',
          ),
          array(
            \'value\' => \'8\',
            \'revision_id\' => \'8\',
          ),
          array(
            \'value\' => \'3\',
            \'revision_id\' => \'3\',
          ),
          array(
            \'value\' => \'7\',
            \'revision_id\' => \'7\',
          ),
          array(
            \'value\' => \'13\',
            \'revision_id\' => \'13\',
          ),
          array(
            \'value\' => \'6\',
            \'revision_id\' => \'6\',
          ),
        ),
      ),
      \'field_top_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'1040\',
            \'uid\' => \'11580\',
            \'filename\' => \'AP-Image_3.jpg\',
            \'uri\' => \'public://images/AP-Image_3.jpg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'103050\',
            \'status\' => \'1\',
            \'timestamp\' => \'1464704920\',
            \'type\' => \'image\',
            \'uuid\' => \'78733386-61d5-4b91-81d5-9fa31101cded\',
            \'image_dimensions\' => array(
              \'width\' => \'1119\',
              \'height\' => \'459\',
            ),
            \'alt\' => NULL,
            \'title\' => NULL,
            \'width\' => \'1119\',
            \'height\' => \'459\',
          ),
        ),
      ),
      \'files\' => array(),
      \'is_current\' => TRUE,
      \'is_pending\' => FALSE,
      \'language\' => \'und\',
      \'last_comment_timestamp\' => NULL,
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'leverenz\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'num_revisions\' => \'6\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'revision_moderation\' => FALSE,
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'11580\',
      \'status\' => \'1\',
      \'sticky\' => \'0\',
      \'title\' => \'Academic Plaza\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'basic_page2\',
      \'uid\' => \'11580\',
      \'uuid\' => \'65941919-0574-4b03-9b6d-30c7e3b2b9b7\',
      \'vid\' => NULL,
      \'vuuid\' => \'745310bd-7cf9-4041-82a4-8d1e5677e10a\',
    ),
)',
);
  return $node_export;
}
